name: Convert MKV to MP4

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Download MKV file
        run: wget "https://kqrumi.xyz/0:findpath?id=16QalfzARBbAAvngdNlH5hGIJihpBWhuf" -O input.mkv

      - name: Convert MKV to MP4
        run: ffmpeg -i input.mkv -vcodec libx264 -acodec aac output.mp4

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Add converted MP4 file"
          add: "output.mp4"
