name: Convert MKV to MP4 and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        python3 -m pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create token.pickle
      run: |
        echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > token.pickle

    - name: Download MKV file
      run: |
        curl -L -o video.mkv "https://kqrumi.xyz/download.aspx?file=whrXhEAGJgOnJvEgcnp1%2BuX96stb7Oqj%2Bd7eBXC8CWcqxMyPPxl5%2FWajYwBtQgsx&expiry=w%2FXTFdPO1yqWFXiBkzvN7w%3D%3D&ip=6wC4ugEAc0cuqCq81hdbsg%3D%3D&mac=d343d91d5b1b85fe00c0328c4ba2da605689429f341d4101754d485daa4592e6"

    - name: Convert MKV to MP4
      run: |
        ffmpeg -i video.mkv -vf "scale=-1:720" -r 23 -b:v 1M -c:v libx264 -c:a copy -c:s mov_text -movflags +faststart video.mp4

    - name: Upload to Google Drive
      run: python3 upload_to_gdrive.py video.mp4
