name: Convert MKV to MP4

on:
  workflow_dispatch:

jobs:
  convert-video:
    runs-on: ubuntu-latest

    steps:
      - name: Download video file
        run: |
          mkdir -p videos
          curl -L "https://kqrumi.xyz/0:findpath?id=16QalfzARBbAAvngdNlH5hGIJihpBWhuf" -o videos/input.mkv

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Convert MKV to MP4
        run: ffmpeg -i videos/input.mkv -c:v copy -c:a copy videos/output.mp4

      - name: Upload converted file
        uses: actions/upload-artifact@v3
        with:
          name: converted-video
          path: videos/output.mp4
